name: Deploy site to Yandex S3
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: List build output
        run: find dist -type f

      - name: Upload files to Yandex Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_CLOUD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_CLOUD_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://${{ secrets.BUCKET }} \
            --endpoint-url https://storage.yandexcloud.net \
            --delete \
            --region ru-central1
