name: Deploy site to Yandex S3
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dist
        run: |
          mkdir -p dist
          cp index.html dist/
          cp streaming.html dist/
          cp sip.html dist/
          cp nop.html dist/
          cp streaming.js dist/
          cp sip.js dist/
          cp janus.js dist/
          cp settings.js dist/
          cp demo.css dist/
          cp favicon.ico dist/

      - name: List build output
        run: find dist -type f

      - name: Upload files to Object Storage
        id: s3-upload
        uses: yc-actions/yc-obj-storage-upload@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ secrets.BUCKET }}
          root: ./dist
          include: |
            **/*.*
            **/*
            *.*
            *
