name: Deploy site to Yandex S3
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Node version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload files to Yandex Object Storage
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.YANDEX_CLOUD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YANDEX_CLOUD_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync ./dist s3://${{ secrets.BUCKET }} \
            --endpoint-url https://storage.yandexcloud.net \
            --delete \
            --region ru-central1
